site_name: My Docs
theme: 
  name: material
nav:
    - Home: 'index.md'
    - '1.1: Basic Rules': 'basics/basics.md'
    - '1.2: Players': 'basics/players.md'
    - '2: Matches': 'matches/matches.md'
    - '3: Servers': 'servers/servers.md'
    - '4: Cheating': 'cheating/cheating.md'
      