site_name: My Docs
theme: 
  name: material
nav:
    - Home: 'index.md'
    - '1.1: Basic Rules': 'basics/basics.md'
    - '1.2: Players': 'basics/players.md'
    - '2: Matches': 'matches/matches.md'
    - '3: Servers': 'servers/servers.md'
    - '4: Cheating': 'cheating/cheating.md'
    - '5: Scripts': 'scripts/scripts.md'  
    - '6: Game Modifications': 'mods/mods.md'
    - '7: Explanations': 'explanations/explanations.md'
    - '8: Maps and Configs': 'maps-configs/maps-and-configs.md'